services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - 5173:3000
    volumes:
      - ./frontend:/frontend
    command: ["pnpm", "dev"]
  backend:
    image: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    command: ["pnpm", "start:dev"]
    depends_on:
      - db

volumes:
  pgdata: {}
