import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/components/ui/font";
import { Providers } from "./Providers";
 import { ToastContainer } from "react-toastify";

 export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
 };

 export default function RootLayout({
   children,
 }: Readonly<{
   children: React.ReactNode;
 }>) {
   return (
     <html lang="en">
       <body className={`${montserrat.className} antialiased`}>
         <Providers>{children}</Providers>
         <ToastContainer />
       </body>
     </html>
   );
 }
